### Get all posts
GET http://localhost:8000/api/posts
Accept: application/json

### Get a specific post by ID
GET http://localhost:8000/api/posts/1
Accept: application/json

### Create a new post
POST http://localhost:8000/api/posts
Content-Type: application/json

{
  "title": "Sample Post4",
  "body": "This is a sample post body."
}

### Update a post
PUT http://localhost:8000/api/posts/1
Content-Type: application/json

{
  "title": "Updated Post Title"
}

### Delete a post
DELETE http://localhost:8000/api/posts/1
Accept: application/json

